### PR TITLE
Fixing GOG achievements for public profiles

### PR DESCRIPTION
**Pull request by Jhanlon95**
Currently SuccessStory cannot get GOG achievements at all, this fixes it if your profile is public. When debugging the regex that was being used wasn't returning any values. I have changed the regex and now it returns correctly.

Here is a regexr script that shows it matches properly on the achievements regexr.com/89bbj.

I have attached a picture of my IDE getting the response correctly as well, the contents of jsonDataString contains the achievement data

image

### CODE REVIEW

**Comment by Lacro59** [comment]
Thanks for identifying the problem.
Wouldn't it be better to do so?
`string pattern = regexForward + @"(\[?{.*}\]?)[;]?[<]?";`
In order to break other calls to this function?

**Comment by Jhanlon95** [comment]
Yeah that would probably be better, I was mainly focused on getting the GOG achievements working again, but checked the Regex you provided and it seems like a better one than I provided. Also renaming the "regexForward" variable is a good idea since it's putting us into the brackets

**Comment by Jhanlon95** [comment]
have updated the regex and the variable name as discussed

**Comment by Kryeker** [comment]
Possible error in Tools.GetJsonInString, Playnite crashes when logging into steam  
image
image

**Comment by Jhanlon95** [comment]
Have raised a PR to fix this, sorry

https://github.com/Lacro59/playnite-plugincommon/pull/139

**Pull request merged**
